### ISSUE TITLE
Plus de remontées de valeurs et erreurs deconz suite au passage vers la V11 en OTA

### ISSUE THREAD

**Issue by maxime-hallard** [fairecasoimeme/Zlinky_TIC#130]
Bonjour,

Je viens de recevoir la clé zlinky.

Environnement:

HA - Z2M - Deconz Conbee2

Après l'avoir branché et appairé, j'ai commencé à recevoir des valeurs.
J'ai fait la mise à jour proposée en OTA, le process semble s'être déroulé correctement.

Suite à cette maj, les valeurs remontées sont figées, et des redémarrages successifs (Zlinky, Z2M, Conbee 2, HA, Raspberry) n'ont rien changé.
Je suis sur les dernières versions pour tous les composants, j'ai pu constater dans les payloads reçus que current_summ_delivered ne s'incrémente plus.

J'a cette erreur qui remontent dans les logs de Z2M lors de ce qui semble être une configuration du reporting pour "seMetering":

Debug 2022-11-10 14:09:58Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure_reporting' with data '{"attribute":"currentSummDelivered","cluster":"seMetering","id":"zlinky/1","maximum_report_interval":900,"minimum_report_interval":60,"reportable_change":100,"transaction":"c30p6-1"}'

Error 2022-11-10 14:09:59Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'Bind 0x00158d0005be9a8a/1 seMetering from '0x00212effff081e75/1' failed (Error: status: 140)'
Debug 2022-11-10 14:09:59Error: Bind 0x00158d0005be9a8a/1 seMetering from '0x00212effff081e75/1' failed (Error: status: 140) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Bridge.deviceConfigureReporting (/app/lib/extension/bridge.ts:444:9) at Bridge.onMQTTMessage (/app/lib/extension/bridge.ts:123:34)

Info 2022-11-10 14:09:59MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"Bind 0x00158d0005be9a8a/1 seMetering from '0x00212effff081e75/1' failed (Error: status: 140)","status":"error","transaction":"c30p6-1"}'

J'ai regardé un peu ce que pouvait vouloir dire ce code erreur 140 remonté par Deconz mais je n'ai rien remonté de probant.

Avez-vous une idée de ce qui peut causer cette erreur, et comment y remédier?

Merci :)

**Comment by maxime-hallard** [comment]
J'ai tenté un réappairage, cela a suffit, mes données remontent à nouveau
